{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-r2dbc",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-spi"
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core"
        }
      ],
      "files": [
        {
          "name": "spring-r2dbc-6.0.0-SNAPSHOT.jar",
          "url": "spring-r2dbc-6.0.0-SNAPSHOT.jar",
          "size": 136763,
          "sha512": "cce2d6351b6352fa68b4f7007daa11dd3f002d956fe97e0cfc019cd0ddb47bbb17f8265720e4b74c44f9231c0022d3d47612d580f42106eee70a8a1db9490f58",
          "sha256": "79a563ff2e7b4e15221199918be0f7e6823745e30ad0b32f5aef7b0621c29ae6",
          "sha1": "9a8729c31e17fd97ae0aac81fc9244df77591989",
          "md5": "f3f18b2fd6d04086c62a23fa6bef1949"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-spi"
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core"
        }
      ],
      "files": [
        {
          "name": "spring-r2dbc-6.0.0-SNAPSHOT.jar",
          "url": "spring-r2dbc-6.0.0-SNAPSHOT.jar",
          "size": 136763,
          "sha512": "cce2d6351b6352fa68b4f7007daa11dd3f002d956fe97e0cfc019cd0ddb47bbb17f8265720e4b74c44f9231c0022d3d47612d580f42106eee70a8a1db9490f58",
          "sha256": "79a563ff2e7b4e15221199918be0f7e6823745e30ad0b32f5aef7b0621c29ae6",
          "sha1": "9a8729c31e17fd97ae0aac81fc9244df77591989",
          "md5": "f3f18b2fd6d04086c62a23fa6bef1949"
        }
      ]
    }
  ]
}
